pluginManagement {
    repositories {
        gradlePluginPortal()
    }
}

rootProject.name = 'taskapi'

include 'bootstrap'
include 'security'
include 'shared-kernel'
include 'web'

include 'user'
include 'task'

project(":bootstrap").projectDir = file("./bootstrap")
project(":security").projectDir = file("./security")
project(":web").projectDir = file("./web")
project(":shared-kernel").projectDir = file("./shared-kernel")

project(":user").projectDir = file("./user")
project(":task").projectDir = file("./task")