//build.gralde ( web )

dependencies{
    implementation project(':shared-kernel')
    implementation project(':security')

    implementation project(':user')
    implementation project(':task')
    // implementation project()

    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.3.0'
}